//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateAnswerFile.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenerateAnswerFile.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates answer files (unattend.xml and autounattend.xml) for unattended Windows installation..
        /// </summary>
        internal static string ApplicationDescription {
            get {
                return ResourceManager.GetString("ApplicationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of times the user will be automatically logged in..
        /// </summary>
        internal static string AutoLogonCountDescription {
            get {
                return ResourceManager.GetString("AutoLogonCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password of the user to automatically log on..
        /// </summary>
        internal static string AutoLogonPasswordDescription {
            get {
                return ResourceManager.GetString("AutoLogonPasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the user (in the format &apos;domain\user&apos;, or just &apos;user&apos; for local users) to automatically log on..
        /// </summary>
        internal static string AutoLogonUserDescription {
            get {
                return ResourceManager.GetString("AutoLogonUserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password of the user used to access the network..
        /// </summary>
        internal static string CmdKeyPasswordDescription {
            get {
                return ResourceManager.GetString("CmdKeyPasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default user used to access the network, in &apos;domain\user&apos; format..
        /// </summary>
        internal static string CmdKeyUserDescription {
            get {
                return ResourceManager.GetString("CmdKeyUserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The network name for the computer..
        /// </summary>
        internal static string ComputerNameDescription {
            get {
                return ResourceManager.GetString("ComputerNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Windows cloud consumer features. This prevents auto-installation of recommended store apps..
        /// </summary>
        internal static string DisableCloudDescription {
            get {
                return ResourceManager.GetString("DisableCloudDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Windows Defender after installation..
        /// </summary>
        internal static string DisableDefenderDesciption {
            get {
                return ResourceManager.GetString("DisableDefenderDesciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Server Manager from starting at first logon (Windows Server only)..
        /// </summary>
        internal static string DisableServerManagerDescription {
            get {
                return ResourceManager.GetString("DisableServerManagerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The display resolution, in the format &apos;width,height&apos;. For example, &apos;1280,1024&apos;. If not specified, the default resolution is determined by Windows..
        /// </summary>
        internal static string DisplayResolutionDescription {
            get {
                return ResourceManager.GetString("DisplayResolutionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of a domain account to add to the local administrators group. Must be in the domain you&apos;re joining. Can have multiple values..
        /// </summary>
        internal static string DomainAccountsDescription {
            get {
                return ResourceManager.GetString("DomainAccountsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain\User.
        /// </summary>
        internal static string DomainUserValueDescription {
            get {
                return ResourceManager.GetString("DomainUserValueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on remote desktop and allow it through the firewall..
        /// </summary>
        internal static string EnableRemoteDesktopDescriptoin {
            get {
                return ResourceManager.GetString("EnableRemoteDesktopDescriptoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feature name of an optional feature to install. Use the PowerShell &apos;Get-WindowsOptionalFeature&apos; command to get a list of valid feature names. Can have multiple values..
        /// </summary>
        internal static string FeaturesDescription {
            get {
                return ResourceManager.GetString("FeaturesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A command to run during first logon. Can have multiple values. Commands are run before the scripts specified by -SetupScript..
        /// </summary>
        internal static string FirstLogonCommandsDescription {
            get {
                return ResourceManager.GetString("FirstLogonCommandsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WIM image index to install. Use this for editions not installed using a product key such as volume license editions. Use the PowerShell &apos;Get-WindowsImage&apos; command to list all images in a .wim or .esd file..
        /// </summary>
        internal static string ImageIndexDescription {
            get {
                return ResourceManager.GetString("ImageIndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The install method to use..
        /// </summary>
        internal static string InstallDescription {
            get {
                return ResourceManager.GetString("InstallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The zero-based ID of the disk to install to. This disk will be wiped and repartitioned according to -Partition, or using the default layout if -Partition is not specified..
        /// </summary>
        internal static string InstallToDiskDescription {
            get {
                return ResourceManager.GetString("InstallToDiskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The one-based ID of the partition to install to on the disk specified by -InstallToDisk. If not specified and -Install is CleanEfi or CleanBios, Windows will be installed on the first regular data partition. If -Install is ExistingPartition, the default value is 3, which is appropriate for UEFI systems with the default partition layout..
        /// </summary>
        internal static string InstallToPartitionDescription {
            get {
                return ResourceManager.GetString("InstallToPartitionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need at least one method..
        /// </summary>
        internal static string InvalidMethodCount {
            get {
                return ResourceManager.GetString("InvalidMethodCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the domain to join..
        /// </summary>
        internal static string JoinDomainDescription {
            get {
                return ResourceManager.GetString("JoinDomainDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password of the user used to join the domain. Will be stored in plain text..
        /// </summary>
        internal static string JoinDomainPasswordDescription {
            get {
                return ResourceManager.GetString("JoinDomainPasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of a user with permission to join the domain. Use the format &apos;domain\user&apos;, or just &apos;user&apos; to if the user is a member of the domain specified with -JoinDomain..
        /// </summary>
        internal static string JoinDomainUserDescription {
            get {
                return ResourceManager.GetString("JoinDomainUserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language used for the UI language and the input, system and user locales..
        /// </summary>
        internal static string LanguageDescription {
            get {
                return ResourceManager.GetString("LanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A local account to add, using the format &apos;name,password&apos;. Can have multiple values..
        /// </summary>
        internal static string LocalAccountsDescription {
            get {
                return ResourceManager.GetString("LocalAccountsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name,Password.
        /// </summary>
        internal static string LocalCredentialValueDescription {
            get {
                return ResourceManager.GetString("LocalCredentialValueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows additional help in your web browser..
        /// </summary>
        internal static string OnlineHelpDescription {
            get {
                return ResourceManager.GetString("OnlineHelpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/SvenGroot/GenerateAnswerFile.
        /// </summary>
        internal static string OnlineHelpUrl {
            get {
                return ResourceManager.GetString("OnlineHelpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Domain\]User.
        /// </summary>
        internal static string OptionalDomainUserValueDescription {
            get {
                return ResourceManager.GetString("OptionalDomainUserValueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The organizational unit to use when joining the domain..
        /// </summary>
        internal static string OUPathDescription {
            get {
                return ResourceManager.GetString("OUPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path and file name to write the answer file to..
        /// </summary>
        internal static string OutputFileDescription {
            get {
                return ResourceManager.GetString("OutputFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A partition to create on the disk specified by -InstallToDisk. Can have multiple values.
        ///Use the format &apos;label:size&apos; or &apos;label:size[fs]&apos;, where label is the volume label, size is the size of the partition and can use multiple-byte units such as GB, and fs is an optional file system like FAT32 or NTFS. For example &apos;System:100MB&apos;, &apos;Windows:128GB&apos;, or &apos;Data:16GB[FAT32]&apos;. Sizes will be truncated to whole megabytes.
        ///Use &apos;*&apos; for the size to extend the partition to fill the remainder of the disk (e.g. &apos;Windows:* [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PartitionsDescription {
            get {
                return ResourceManager.GetString("PartitionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label:Size.
        /// </summary>
        internal static string PartitionsValueDescription {
            get {
                return ResourceManager.GetString("PartitionsValueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string PathValueDescription {
            get {
                return ResourceManager.GetString("PathValueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The processor architecture of the Windows edition you&apos;re installing. Use amd64 for 64 bit, and x86 for 32 bit..
        /// </summary>
        internal static string ProcessorArchitectureDescription {
            get {
                return ResourceManager.GetString("ProcessorArchitectureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product key used to select what edition to install and to activate Windows..
        /// </summary>
        internal static string ProductKeyDescription {
            get {
                return ResourceManager.GetString("ProductKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The full path of a Windows PowerShell script to run during first logon. Can have multiple values. Scripts are run after the commands specified by -FirstLogonCommand..
        /// </summary>
        internal static string SetupScriptsDescription {
            get {
                return ResourceManager.GetString("SetupScriptsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time zone that Windows will use. Run &apos;tzutil /l&apos; for a list of valid values..
        /// </summary>
        internal static string TimeZoneDescription {
            get {
                return ResourceManager.GetString("TimeZoneDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information, as well as usage examples, run &apos;{0} -OnlineHelp&apos;, or see: https://github.com/SvenGroot/GenerateAnswerFile.
        /// </summary>
        internal static string UsageHelpFooterFormat {
            get {
                return ResourceManager.GetString("UsageHelpFooterFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; argument may only be used if -Install is set to {1}..
        /// </summary>
        internal static string ValidateInstallMethodErrorFormat {
            get {
                return ResourceManager.GetString("ValidateInstallMethodErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May only be used if -Install is set to {0}..
        /// </summary>
        internal static string ValidateInstallMethodUsageFormat {
            get {
                return ResourceManager.GetString("ValidateInstallMethodUsageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version and build number (e.g. 10.0.22000.1) of the OS being installed. This argument is only used when -Feature is specified..
        /// </summary>
        internal static string WindowsVersionDescription {
            get {
                return ResourceManager.GetString("WindowsVersionDescription", resourceCulture);
            }
        }
    }
}
